# Generated by Django 2.2 on 2019-05-23 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_timelog_time_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='work_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='work_time',
            field=models.TimeField(default=datetime.time(9, 0), null=True),
        ),
    ]
