# Generated by Django 2.2 on 2019-06-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190523_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelog',
            name='work_time',
        ),
    ]
